# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f2c1c36de9d325d6090946f8f1cfc0225b9ab03b4adc38d7e0644f89333510df5e05e7fb19ba550ed28f0da2497ba6bd41d5cdf028d68db9821186bd4092d7

test:
  secret_key_base: b1da06e6577e07007a1275b8f08cb30747924233b3b65d758667b22970b724823eaeafc1d6c083e117daf999a6d006916811788ea395342c392a8e74987e79e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
